version: '3.2'
services:
    containerids:
        image: "joseluiseiguren/ids:release8"
        ports:
            - "8080:5000"
        environment:
            - ConnectionStrings:users_and_clients_database="este es mi connection string"
            - urlsConfiguration:redirectWebSite1=http://localhost:9992/signin-oidc
            - urlsConfiguration:logoutWebSite1=http://localhost:9992/signout-callback-oidc
            - urlsConfiguration:redirectWebSite2=http://localhost:9993/signin-oidc
            - urlsConfiguration:logoutWebSite2=http://localhost:9993/signout-callback-oidc
            - Logging:LogLevel:Default=Information
            - idsconfig:issuer=http://containerids:5000
        volumes:
            - type: bind
              source: ./logids
              target: /app/Logs
              
    containerwebapi:
        image: "joseluiseiguren/wapi:release1"
        ports:
            - "8081:5001"
        environment:
            - urlsConfiguration:authority=http://containerids:5000
        volumes:
            - type: bind
              source: ./logwebapi
              target: /app/Logs
